// op.idl: op 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 生成类型库(op.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";
//
//[
//	object,
//	uuid(a817e7a2-43fa-11d0-9e44-00aa00b6770a),
//	dual,
//	pointer_default(unique)
//]
//interface IComponentRegistrar : IDispatch
//{
//	[id(1)]	HRESULT Attach([in] BSTR bstrPath);
//	[id(2)]	HRESULT RegisterAll();
//	[id(3)]	HRESULT UnregisterAll();
//	[id(4)]	HRESULT GetComponents([out] SAFEARRAY(BSTR)* pbstrCLSIDs, [out] SAFEARRAY(BSTR)* pbstrDescriptions);
//	[id(5)]	HRESULT RegisterComponent([in] BSTR bstrCLSID);
//	[id(6)] HRESULT UnregisterComponent([in] BSTR bstrCLSID);
//};

[
	object,
	uuid(85f31925-b7ce-4e26-918e-082893bde6ff),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IOpAutomation : IDispatch
{
	//base config 1-19
	[id(1)] HRESULT RuntimeVer([out, retval] BSTR* ret);
	[id(2)] HRESULT RuntimeSetPath([in]BSTR path, [out, retval] LONG* ret);
	[id(3)] HRESULT RuntimeGetPath([out, retval] BSTR* path);
	[id(4)] HRESULT RuntimeGetBasePath([out, retval] BSTR* path);
	[id(5)] HRESULT RuntimeGetID([out, retval] LONG* ret);
	[id(6)] HRESULT RuntimeGetLastError([out, retval] LONG* ret);
	[id(7)] HRESULT RuntimeSetShowErrorMsg([in] LONG show_type, [out, retval] LONG* ret);
	[id(8)] HRESULT RuntimeSleep([in] LONG millseconds, [out, retval] LONG* ret);
	[id(9)] HRESULT WindowInjectDll([in] BSTR process_name, [in] BSTR dll_name, [out, retval] LONG* ret);
	[id(10)] HRESULT ImageEnablePicCache([in] LONG enable, [out, retval] LONG* ret);
	[id(11)] HRESULT ImageCapturePre([in]BSTR file_name, [out, retval] LONG* ret);
	//algorithm 20-49
	[id(20)] HRESULT AlgorithmAStarFindPath([in] LONG mapWidth, [in] LONG mapHeight, [in] BSTR disable_points, [in] LONG beginX, [in] LONG beginY, [in] LONG endX, [in] LONG endY, [out, retval] BSTR* path);
	[id(21)] HRESULT AlgorithmFindNearestPos([in] BSTR all_pos, [in] LONG type, [in] LONG x, [in] LONG y, [out, retval] BSTR* retstr);
	//windows api 50-99
	[id(58)] HRESULT WindowEnumWindow([in] hyper parent, [in] BSTR title, [in] BSTR class_name, [in] LONG filter, [out, retval] BSTR* retstr);
	[id(59)] HRESULT WindowEnumWindowByProcess([in] BSTR process_name, [in] BSTR title, [in] BSTR class_name, [in] LONG filter, [out, retval] BSTR* retstring);
	[id(60)] HRESULT WindowEnumProcess([in] BSTR name, [out, retval] BSTR* retstring);
	[id(61)] HRESULT WindowClientToScreen([in] hyper hwnd, [in, out] VARIANT* x, [in, out] VARIANT* y, [out, retval] LONG* bret);
	[id(62)] HRESULT WindowFindWindow([in] BSTR class_name, [in] BSTR title, [out, retval] hyper* rethwnd);
	[id(63)] HRESULT WindowFindWindowByProcess([in] BSTR process_name, [in] BSTR class_name, [in] BSTR title, [out, retval] hyper* rethwnd);
	[id(64)] HRESULT WindowFindWindowByProcessId([in] LONG process_id, [in] BSTR class_name, [in] BSTR title, [out, retval] hyper* rethwnd);
	[id(65)] HRESULT WindowFindWindowEx([in] hyper parent, [in] BSTR class_name, [in] BSTR title, [out, retval] hyper* rethwnd);
	[id(66)] HRESULT WindowGetClientRect([in] hyper hwnd, [out] VARIANT* x1, [out] VARIANT* y1, [out] VARIANT* x2, [out] VARIANT* y2, [out, retval] LONG* nret);
	[id(67)] HRESULT WindowGetClientSize([in] hyper hwnd, [out] VARIANT* width, [out] VARIANT* height, [out, retval] LONG* nret);
	[id(68)] HRESULT WindowGetForegroundFocus([out, retval] hyper* rethwnd);
	[id(69)] HRESULT WindowGetForegroundWindow([out, retval] hyper* rethwnd);
	[id(70)] HRESULT WindowGetMousePointWindow([out, retval] hyper* rethwnd);
	[id(71)] HRESULT WindowGetPointWindow([in] LONG x, [in] LONG y, [out, retval] hyper* rethwnd);
	[id(72)] HRESULT WindowGetProcessInfo([in] LONG pid, [out, retval] BSTR* retstring);
	[id(73)] HRESULT WindowGetSpecialWindow([in] LONG flag, [out, retval] hyper* rethwnd);
	[id(74)] HRESULT WindowGetWindow([in] hyper hwnd, [in] LONG flag, [out, retval] hyper* nret);
	[id(75)] HRESULT WindowGetWindowClass([in] hyper hwnd, [out, retval] BSTR* retstring);
	[id(76)] HRESULT WindowGetWindowProcessId([in] hyper hwnd, [out, retval] LONG* nretpid);
	[id(77)] HRESULT WindowGetWindowProcessPath([in] hyper hwnd, [out, retval] BSTR* retstring);
	[id(78)] HRESULT WindowGetWindowRect([in] hyper hwnd, [out] VARIANT* x1, [out] VARIANT* y1, [out] VARIANT* x2, [out] VARIANT* y2, [out, retval] LONG* nret);
	[id(79)] HRESULT WindowGetWindowState([in] hyper hwnd, [in] LONG flag, [out, retval] LONG* rethwnd);
	[id(80)] HRESULT WindowGetWindowTitle([in] hyper hwnd, [out, retval] BSTR* rettitle);
	[id(81)] HRESULT WindowMoveWindow([in] hyper hwnd, [in] LONG x, [in] LONG y, [out, retval] LONG* nret);
	[id(82)] HRESULT WindowScreenToClient([in] hyper hwnd, [in, out] VARIANT* x, [in, out] VARIANT* y, [out, retval] LONG* nret);
	[id(83)] HRESULT WindowSendPaste([in] hyper hwnd, [out, retval] LONG* nret);
	[id(84)] HRESULT WindowSetClientSize([in] hyper hwnd, [in] LONG width, [in] LONG hight, [out, retval] LONG* nret);
	[id(85)] HRESULT WindowSetWindowState([in] hyper hwnd, [in] LONG flag, [out, retval] LONG* nret);
	[id(86)] HRESULT WindowSetWindowSize([in] hyper hwnd, [in] LONG width, [in] LONG height, [out, retval] LONG* nret);
	[id(87)] HRESULT WindowSetWindowText([in] hyper hwnd, [in] BSTR title, [out, retval] LONG* nret);
	[id(88)] HRESULT WindowSetWindowTransparent([in] hyper hwnd, [in] LONG trans, [out, retval] LONG* nret);
	[id(89)] HRESULT WindowSendString([in] hyper hwnd, [in] BSTR str, [out, retval] LONG* ret);
	[id(90)] HRESULT WindowSendStringIme([in] hyper hwnd, [in] BSTR str, [out, retval] LONG* ret);
	[id(91)] HRESULT WindowRunApp([in] BSTR cmdline, [in] LONG mode, [out] ULONG* pid, [out, retval] LONG* ret);
	[id(92)] HRESULT WindowLayoutWindows([in] BSTR hwnds, [in] LONG layout_type, [in] LONG columns, [in] LONG start_x, [in] LONG start_y, [in] LONG gap_x, [in] LONG gap_y, [in] LONG size_mode, [in] LONG window_width, [in] LONG window_height, [in] LONG anchor_mode, [out, retval] LONG* ret);
	[id(95)] HRESULT WindowWinExec([in] BSTR cmdline, [in] LONG cmdshow, [out, retval] LONG* ret);
	[id(96)] HRESULT WindowGetCmdStr([in] BSTR cmd, [in] LONG millseconds, [out, retval] BSTR* retstr);
	//background 100-119
	[id(100)] HRESULT BindingBindWindow([in] hyper hwnd, [in] BSTR display, [in] BSTR mouse, [in] BSTR keypad, [in] LONG mode, [out, retval] LONG* ret);
	[id(101)] HRESULT BindingUnBindWindow([out, retval] LONG* ret);
	[id(102)] HRESULT BindingGetBindWindow([out, retval] hyper* ret);
	[id(103)] HRESULT BindingIsBind([out, retval] LONG* ret);
	[id(104)] HRESULT BindingBindWindowEx([in] hyper display_hwnd, [in] hyper input_hwnd, [in] BSTR display, [in] BSTR mouse, [in] BSTR keypad, [in] LONG mode, [out, retval] LONG* ret);
	//mouse & ketboard 120-149
	[id(120)] HRESULT MouseGetCursorPos([out] VARIANT* x, [out] VARIANT* y, [out, retval] LONG* ret);
	[id(121)] HRESULT MouseMoveR([in] LONG x, [in] LONG y, [out, retval] LONG* ret);
	[id(122)] HRESULT MouseMoveTo([in] LONG x, [in] LONG y, [out, retval] LONG* ret);
	[id(123)] HRESULT MouseMoveToEx([in] LONG x, [in] LONG y, [in] LONG w, [in] long h, [out, retval] BSTR* ret);

	[id(124)] HRESULT MouseLeftClick([out, retval] LONG* ret);
	[id(125)] HRESULT MouseLeftDoubleClick([out, retval] LONG* ret);
	[id(126)] HRESULT MouseLeftDown([out, retval] LONG* ret);
	[id(127)] HRESULT MouseLeftUp([out, retval] LONG* ret);

	[id(128)] HRESULT MouseMiddleClick([out, retval] LONG* ret);
	[id(129)] HRESULT MouseMiddleDown([out, retval] LONG* ret);
	[id(130)] HRESULT MouseMiddleUp([out, retval] LONG* ret);

	[id(131)] HRESULT MouseRightClick([out, retval] LONG* ret);
	[id(132)] HRESULT MouseRightDown([out, retval] LONG* ret);
	[id(133)] HRESULT MouseRightUp([out, retval] LONG* ret);

	[id(134)] HRESULT MouseWheelDown([out, retval] LONG* ret);
	[id(135)] HRESULT MouseWheelUp([out, retval] LONG* ret);

	[id(136)] HRESULT KeyboardGetKeyState([in] LONG vk_code, [out, retval] LONG* ret);

	[id(137)] HRESULT KeyboardKeyDown([in] LONG vk_code, [out, retval] LONG* ret);
	[id(138)] HRESULT KeyboardKeyDownChar([in] BSTR vk_code, [out, retval] LONG* ret);
	[id(139)] HRESULT KeyboardKeyUp([in] LONG vk_code, [out, retval] LONG* ret);
	[id(140)] HRESULT KeyboardKeyUpChar([in] BSTR vk_code, [out, retval] LONG* ret);
	[id(141)] HRESULT KeyboardWaitKey([in] LONG vk_code, [in] LONG time_out, [out, retval] LONG* ret);
	[id(142)] HRESULT KeyboardKeyPress([in] LONG vk_code, [out, retval] LONG* ret);
	[id(143)] HRESULT KeyboardKeyPressChar([in] BSTR vk_code, [out, retval] LONG* ret);
	[id(144)] HRESULT MouseGetCursorShape([out, retval] BSTR* ret);
	//image & color 150-199
	[id(150)] HRESULT ImageCapture([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR file_name, [out, retval] LONG* ret);
	[id(151)] HRESULT ImageCmpColor([in] LONG x, [in] LONG y, [in] BSTR color, [in] DOUBLE sim, [out, retval] LONG* ret);
	[id(152)] HRESULT ImageFindColor([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] DOUBLE sim, [in] LONG dir, [out] VARIANT* x, [out] VARIANT* y, [out, retval] LONG* ret);
	[id(153)] HRESULT ImageFindColorEx([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] DOUBLE sim, [in] LONG dir, [out, retval] BSTR* retstr);
	[id(154)] HRESULT ImageFindMultiColor([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR first_color, [in] BSTR offset_color, [in] DOUBLE sim, [in] LONG dir, [out] VARIANT* x, [out] VARIANT* y, [out, retval] LONG* ret);
	[id(155)] HRESULT ImageFindMultiColorEx([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR first_color, [in] BSTR offset_color, [in] DOUBLE sim, [in] LONG dir, [out, retval] BSTR* ret);
	[id(156)] HRESULT ImageFindPic([in] LONG x1, [in]LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR files, [in] BSTR delta_color, [in] DOUBLE sim, [in] LONG dir, [out] VARIANT* x, [out] VARIANT* y, [out, retval] LONG* ret);
	[id(157)] HRESULT ImageFindPicEx([in] LONG x1, [in]LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR files, [in] BSTR delta_color, [in] DOUBLE sim, [in] LONG dir, [out, retval] BSTR* retstr);
	//new
	[id(158)] HRESULT ImageFindPicExS([in] LONG x1, [in]LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR files, [in] BSTR delta_color, [in] DOUBLE sim, [in] LONG dir, [out, retval] BSTR* retstr);
	[id(159)] HRESULT ImageFindColorBlock([in] LONG x1, [in]LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] DOUBLE sim, [in] LONG count, [in] LONG height, [in] LONG width, [out] VARIANT* x, [out] VARIANT* y, [out, retval] LONG* ret);
	[id(160)] HRESULT ImageFindColorBlockEx([in] LONG x1, [in]LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] DOUBLE sim, [in] LONG count, [in] LONG height, [in] LONG width, [out, retval] BSTR* retstr);

	[id(163)] HRESULT ImageGetColor([in] LONG x, [in] LONG y, [out, retval] BSTR* ret);
	[id(164)] HRESULT ImageSetDisplayInput([in] BSTR method, [out, retval] LONG* ret);
	[id(165)] HRESULT ImageLoadPic([in] BSTR pic_name, [out, retval] LONG* ret);
	[id(166)] HRESULT ImageFreePic([in] BSTR Pic_name, [out, retval] LONG* ret);
	[id(167)] HRESULT ImageGetScreenData([in] LONG  x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [out, retval]LONG* ret);
	[id(168)] HRESULT ImageGetScreenDataBmp([in] LONG  x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [out] VARIANT* data, [out] VARIANT* size, [out, retval]LONG* ret);
	[id(169)] HRESULT ImageMatchPicName([in] BSTR pic_name, [out, retval] BSTR* retstr);
	[id(170)] HRESULT ImageLoadMemPic([in] BSTR pic_name, [in]long long data, [in]LONG size,[out, retval] LONG* ret);
	[id(171)] HRESULT MouseSetMouseDelay([in] BSTR type, [in] LONG delay, [out, retval]LONG* ret);
	[id(172)] HRESULT KeyboardSetKeypadDelay([in] BSTR type, [in] LONG delay, [out, retval]LONG* ret);
    [id(173)] HRESULT WindowSetClipboard([in] BSTR str, [out, retval] LONG* ret);
    [id(174)] HRESULT WindowGetClipboard([out, retval] BSTR* ret);
    [id(175)] HRESULT RuntimeDelay([in] LONG mis, [out, retval] LONG* ret);
    [id(176)] HRESULT RuntimeDelays([in] LONG mis_min,[in] LONG mis_max, [out, retval] LONG* ret);
	[id(177)] HRESULT KeyboardKeyPressStr([in]BSTR key_str,[in]LONG delay,[out, retval] LONG* ret);
	[id(178)] HRESULT ImageGetColorNum([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] DOUBLE sim, [out, retval]LONG* ret);
	[id(179)] HRESULT ImageGetPicSize([in] BSTR pic_name, [out] VARIANT* width, [out] VARIANT* height, [out, retval] LONG* ret);
	
	//ocr 200-230
	[id(200)] HRESULT OcrSetDict([in] LONG idx, [in] BSTR file_name, [out, retval] LONG* ret);
	[id(201)] HRESULT OcrUseDict([in] LONG idx, [out, retval] LONG* ret);
	[id(202)] HRESULT OcrRecognize([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] DOUBLE sim, [out, retval] BSTR* ret_str);
	[id(203)] HRESULT OcrRecognizeEx([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] DOUBLE sim, [out, retval] BSTR* ret_str);
	[id(204)] HRESULT OcrFindStr([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR str, [in] BSTR color, [in] DOUBLE sim, [out] VARIANT* retx, [out] VARIANT* rety, [out, retval]LONG* ret);
	[id(205)] HRESULT OcrFindStrEx([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR str, [in] BSTR color, [in] DOUBLE sim, [out, retval] BSTR* ret_str);
	[id(206)] HRESULT OcrRecognizeAuto([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] DOUBLE sim, [out, retval] BSTR* retstr);
	[id(207)] HRESULT OcrRecognizeFromFile([in] BSTR file_name, [in] BSTR color_format, [in] DOUBLE sim, [out, retval] BSTR* retstr);
	[id(208)] HRESULT OcrRecognizeAutoFromFile([in] BSTR file_name, [in] DOUBLE sim, [out, retval] BSTR* retstr);
	[id(209)] HRESULT OcrFindLine([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] DOUBLE sim, [out, retval] BSTR* retstr);
	[id(210)] HRESULT OcrSetEngine([in] BSTR path_of_engine, [in] BSTR dll_name, [in] BSTR argv, [out, retval] LONG* ret);
	[id(211)] HRESULT YoloSetEngine([in] BSTR path_of_engine, [in] BSTR dll_name, [in] BSTR argv, [out, retval] LONG* ret);
	[id(212)] HRESULT YoloDetect([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] DOUBLE conf, [in] DOUBLE iou, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(213)] HRESULT YoloDetectFromFile([in] BSTR file_name, [in] DOUBLE conf, [in] DOUBLE iou, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(220)] HRESULT OcrSetMemDict([in] LONG idx, [in]BSTR data, [in]LONG size, [out, retval] LONG* ret);
	[id(221)] HRESULT OcrGetDict([in] LONG idx, [in] LONG font_index, [out, retval] BSTR* retstr);
	[id(222)] HRESULT OcrAddDict([in] LONG idx, [in] BSTR dict_info, [out, retval] LONG* ret);
	[id(223)] HRESULT OcrSaveDict([in] LONG idx, [in] BSTR file_name, [out, retval] LONG* ret);
	[id(224)] HRESULT OcrClearDict([in] LONG idx, [out, retval] LONG* ret);
	[id(225)] HRESULT OcrGetDictCount([in] LONG idx, [out, retval] LONG* ret);
	[id(226)] HRESULT OcrGetNowDict([out, retval] LONG* ret);
	[id(227)] HRESULT OcrFetchWord([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [in] BSTR word, [out, retval] BSTR* retstr);
	[id(228)] HRESULT OcrGetWordsNoDict([in] LONG x1, [in] LONG y1, [in] LONG x2, [in] LONG y2, [in] BSTR color, [out, retval] BSTR* retstr);
	[id(229)] HRESULT OcrGetWordResultCount([in] BSTR result, [out, retval] LONG* ret);
	[id(230)] HRESULT OcrGetWordResultPos([in] BSTR result, [in] LONG index, [out] VARIANT* x, [out] VARIANT* y, [out, retval] LONG* ret);
	[id(231)] HRESULT OcrGetWordResultStr([in] BSTR result, [in] LONG index, [out, retval] BSTR* retstr);

	[id(250)] HRESULT MemoryWriteData([in] hyper hwnd, [in]BSTR address, [in] BSTR data, [in] LONG size, [out, retval] LONG* ret);
	[id(251)] HRESULT MemoryReadData([in] hyper hwnd, [in] BSTR address, [in] LONG size, [out, retval] BSTR* retstr);
	[id(252)] HRESULT MemoryReadInt([in] hyper hwnd, [in] BSTR address, [in] LONG type, [out, retval] hyper* ret);
	[id(253)] HRESULT MemoryWriteInt([in] hyper hwnd, [in] BSTR address, [in] LONG type, [in] hyper value, [out, retval] LONG* ret);
	[id(254)] HRESULT MemoryReadFloat([in] hyper hwnd, [in] BSTR address, [out, retval] DOUBLE* ret);
	[id(255)] HRESULT MemoryWriteFloat([in] hyper hwnd, [in] BSTR address, [in] DOUBLE value, [out, retval] LONG* ret);
	[id(256)] HRESULT MemoryReadDouble([in] hyper hwnd, [in] BSTR address, [out, retval] DOUBLE* ret);
	[id(257)] HRESULT MemoryWriteDouble([in] hyper hwnd, [in] BSTR address, [in] DOUBLE value, [out, retval] LONG* ret);
	[id(258)] HRESULT MemoryReadString([in] hyper hwnd, [in] BSTR address, [in] LONG type, [in] LONG len, [out, retval] BSTR* retstr);
	[id(259)] HRESULT MemoryWriteString([in] hyper hwnd, [in] BSTR address, [in] LONG type, [in] BSTR value, [out, retval] LONG* ret);
	[id(300)] HRESULT OpenCvLoadTemplate([in] BSTR name, [in] BSTR file_path, [out, retval] LONG* ret);
	[id(301)] HRESULT OpenCvLoadMaskedTemplate([in] BSTR name, [in] BSTR template_path, [in] BSTR mask_path, [out, retval] LONG* ret);
	[id(302)] HRESULT OpenCvRemoveTemplate([in] BSTR name, [out, retval] LONG* ret);
	[id(303)] HRESULT OpenCvRemoveAllTemplates([out, retval] LONG* ret);
	[id(304)] HRESULT OpenCvHasTemplate([in] BSTR name, [out, retval] LONG* ret);
	[id(305)] HRESULT OpenCvGetTemplateCount([out, retval] LONG* ret);
	[id(306)] HRESULT OpenCvGetAllTemplateNames([out, retval] BSTR* retstr);
	[id(307)] HRESULT OpenCvGetOpenCvVersion([out, retval] BSTR* retstr);
	[id(308)] HRESULT OpenCvLoadTemplateList([in] BSTR template_list, [out, retval] LONG* ret);
	[id(310)] HRESULT OpenCvMatchTemplate([in] LONG x, [in] LONG y, [in] LONG width, [in] LONG height, [in] BSTR template_name, [in] DOUBLE threshold, [in] LONG dir, [in] LONG strip_mode, [in] LONG method, [in] LONG color_mode, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(311)] HRESULT OpenCvMatchTemplateScale([in] LONG x, [in] LONG y, [in] LONG width, [in] LONG height, [in] BSTR template_name, [in] BSTR scales, [in] DOUBLE threshold, [in] LONG method, [in] LONG color_mode, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(312)] HRESULT OpenCvMatchAnyTemplate([in] LONG x, [in] LONG y, [in] LONG width, [in] LONG height, [in] BSTR template_names, [in] DOUBLE threshold, [in] LONG dir, [in] LONG strip_mode, [in] LONG method, [in] LONG color_mode, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(313)] HRESULT OpenCvMatchAllTemplates([in] LONG x, [in] LONG y, [in] LONG width, [in] LONG height, [in] BSTR template_names, [in] DOUBLE threshold, [in] LONG dir, [in] LONG strip_mode, [in] LONG method, [in] LONG color_mode, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(314)] HRESULT OpenCvFeatureMatchTemplate([in] LONG x, [in] LONG y, [in] LONG width, [in] LONG height, [in] BSTR template_name, [in] DOUBLE threshold, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(315)] HRESULT OpenCvEdgeMatchTemplate([in] LONG x, [in] LONG y, [in] LONG width, [in] LONG height, [in] BSTR template_name, [in] DOUBLE threshold, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(316)] HRESULT OpenCvShapeMatchTemplate([in] LONG x, [in] LONG y, [in] LONG width, [in] LONG height, [in] BSTR template_name, [in] DOUBLE threshold, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(317)] HRESULT OpenCvToGray([in] BSTR src_file, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(318)] HRESULT OpenCvCrop([in] BSTR src_file, [in] LONG x, [in] LONG y, [in] LONG width, [in] LONG height, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(319)] HRESULT OpenCvResize([in] BSTR src_file, [in] LONG width, [in] LONG height, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(320)] HRESULT OpenCvThreshold([in] BSTR src_file, [in] BSTR dst_file, [in] DOUBLE threshold, [in] DOUBLE max_value, [in] BSTR mode, [out, retval] LONG* ret);
	[id(321)] HRESULT OpenCvInRange([in] BSTR src_file, [in] BSTR dst_file, [in] BSTR color_space, [in] BSTR lower, [in] BSTR upper, [out, retval] LONG* ret);
	[id(322)] HRESULT OpenCvMorphology([in] BSTR src_file, [in] BSTR dst_file, [in] BSTR mode, [in] LONG kernel_size, [in] LONG iterations, [out, retval] LONG* ret);
	[id(323)] HRESULT OpenCvThin([in] BSTR src_file, [in] BSTR dst_file, [in] BSTR mode, [out, retval] LONG* ret);
	[id(324)] HRESULT OpenCvToBinary([in] BSTR src_file, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(325)] HRESULT OpenCvToEdge([in] BSTR src_file, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(326)] HRESULT OpenCvToOutline([in] BSTR src_file, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(327)] HRESULT OpenCvDenoise([in] BSTR src_file, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(328)] HRESULT OpenCvCropValid([in] BSTR src_file, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(329)] HRESULT OpenCvEqualize([in] BSTR src_file, [in] BSTR dst_file, [out, retval] LONG* ret);
	[id(330)] HRESULT OpenCvCLAHE([in] BSTR src_file, [in] BSTR dst_file, [in] DOUBLE clip_limit, [in] LONG tile_grid_size, [out, retval] LONG* ret);
	[id(331)] HRESULT OpenCvBlur([in] BSTR src_file, [in] BSTR dst_file, [in] BSTR mode, [in] LONG kernel_size, [out, retval] LONG* ret);
	[id(332)] HRESULT OpenCvSharpen([in] BSTR src_file, [in] BSTR dst_file, [in] DOUBLE strength, [out, retval] LONG* ret);
	[id(333)] HRESULT OpenCvConnectedComponents([in] BSTR src_file, [in] DOUBLE min_area, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(334)] HRESULT OpenCvFindContours([in] BSTR src_file, [in] DOUBLE min_area, [out] BSTR* retjson, [out, retval] LONG* ret);
	[id(335)] HRESULT OpenCvPreprocessPipeline([in] BSTR src_file, [in] BSTR dst_file, [in] BSTR pipeline, [out, retval] LONG* ret);



};
[
	uuid(40297cce-e4de-4d31-acfb-81bb8d14d261),
	version(1.0),
	custom(a817e7a1-43fa-11d0-9e44-00aa00b6770a, "{54ca0535-fb49-4d91-8709-786fb8725132}")
]
library opLib
{
	importlib("stdole2.tlb");
	/*[
		uuid(54ca0535-fb49-4d91-8709-786fb8725132)
	]
	coclass CompReg
	{
		[default] interface IComponentRegistrar;
	};*/
	[
		uuid(6d0fe2a0-f265-4961-9f92-ec22b64fb80c)
	]
	coclass OpAutomation
	{
		[default] interface IOpAutomation;
	};
};

import "shobjidl.idl";

