/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

#define SWIG_VERSION 0x040101
#define SWIGCSHARP

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
#if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#define SWIGTEMPLATEDISAMBIGUATOR template
#elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#define SWIGTEMPLATEDISAMBIGUATOR template
#else
#define SWIGTEMPLATEDISAMBIGUATOR
#endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
#if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#define SWIGINLINE inline
#else
#define SWIGINLINE
#endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
#if defined(__GNUC__)
#if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#define SWIGUNUSED __attribute__((__unused__))
#else
#define SWIGUNUSED
#endif
#elif defined(__ICC)
#define SWIGUNUSED __attribute__((__unused__))
#else
#define SWIGUNUSED
#endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
#if defined(_MSC_VER)
#pragma warning(disable : 4505) /* unreferenced local function has been removed */
#endif
#endif

#ifndef SWIGUNUSEDPARM
#ifdef __cplusplus
#define SWIGUNUSEDPARM(p)
#else
#define SWIGUNUSEDPARM(p) p SWIGUNUSED
#endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
#define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
#define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#ifndef GCC_HASCLASSVISIBILITY
#define GCC_HASCLASSVISIBILITY
#endif
#endif
#endif

#ifndef SWIGEXPORT
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#if defined(STATIC_LINKED)
#define SWIGEXPORT
#else
#define SWIGEXPORT __declspec(dllexport)
#endif
#else
#if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#define SWIGEXPORT __attribute__((visibility("default")))
#else
#define SWIGEXPORT
#endif
#endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
#if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#define SWIGSTDCALL __stdcall
#else
#define SWIGSTDCALL
#endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
#define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
#define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
#define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
#pragma warning disable 592
#endif

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Support for throwing C# exceptions from C/C++. There are two types:
 * Exceptions that take a message and ArgumentExceptions that take a message and a parameter name. */
typedef enum {
    SWIG_CSharpApplicationException,
    SWIG_CSharpArithmeticException,
    SWIG_CSharpDivideByZeroException,
    SWIG_CSharpIndexOutOfRangeException,
    SWIG_CSharpInvalidCastException,
    SWIG_CSharpInvalidOperationException,
    SWIG_CSharpIOException,
    SWIG_CSharpNullReferenceException,
    SWIG_CSharpOutOfMemoryException,
    SWIG_CSharpOverflowException,
    SWIG_CSharpSystemException
} SWIG_CSharpExceptionCodes;

typedef enum {
    SWIG_CSharpArgumentException,
    SWIG_CSharpArgumentNullException,
    SWIG_CSharpArgumentOutOfRangeException
} SWIG_CSharpExceptionArgumentCodes;

typedef void(SWIGSTDCALL *SWIG_CSharpExceptionCallback_t)(const char *);
typedef void(SWIGSTDCALL *SWIG_CSharpExceptionArgumentCallback_t)(const char *, const char *);

typedef struct {
    SWIG_CSharpExceptionCodes code;
    SWIG_CSharpExceptionCallback_t callback;
} SWIG_CSharpException_t;

typedef struct {
    SWIG_CSharpExceptionArgumentCodes code;
    SWIG_CSharpExceptionArgumentCallback_t callback;
} SWIG_CSharpExceptionArgument_t;

static SWIG_CSharpException_t SWIG_csharp_exceptions[] = {
    {SWIG_CSharpApplicationException, NULL},  {SWIG_CSharpArithmeticException, NULL},
    {SWIG_CSharpDivideByZeroException, NULL}, {SWIG_CSharpIndexOutOfRangeException, NULL},
    {SWIG_CSharpInvalidCastException, NULL},  {SWIG_CSharpInvalidOperationException, NULL},
    {SWIG_CSharpIOException, NULL},           {SWIG_CSharpNullReferenceException, NULL},
    {SWIG_CSharpOutOfMemoryException, NULL},  {SWIG_CSharpOverflowException, NULL},
    {SWIG_CSharpSystemException, NULL}};

static SWIG_CSharpExceptionArgument_t SWIG_csharp_exceptions_argument[] = {
    {SWIG_CSharpArgumentException, NULL},
    {SWIG_CSharpArgumentNullException, NULL},
    {SWIG_CSharpArgumentOutOfRangeException, NULL}};

static void SWIGUNUSED SWIG_CSharpSetPendingException(SWIG_CSharpExceptionCodes code, const char *msg) {
    SWIG_CSharpExceptionCallback_t callback = SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback;
    if ((size_t)code < sizeof(SWIG_csharp_exceptions) / sizeof(SWIG_CSharpException_t)) {
        callback = SWIG_csharp_exceptions[code].callback;
    }
    callback(msg);
}

static void SWIGUNUSED SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpExceptionArgumentCodes code, const char *msg,
                                                              const char *param_name) {
    SWIG_CSharpExceptionArgumentCallback_t callback =
        SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback;
    if ((size_t)code < sizeof(SWIG_csharp_exceptions_argument) / sizeof(SWIG_CSharpExceptionArgument_t)) {
        callback = SWIG_csharp_exceptions_argument[code].callback;
    }
    callback(msg, param_name);
}

#ifdef __cplusplus
extern "C"
#endif
    SWIGEXPORT void SWIGSTDCALL
    SWIGRegisterExceptionCallbacks_opEx(
        SWIG_CSharpExceptionCallback_t applicationCallback, SWIG_CSharpExceptionCallback_t arithmeticCallback,
        SWIG_CSharpExceptionCallback_t divideByZeroCallback, SWIG_CSharpExceptionCallback_t indexOutOfRangeCallback,
        SWIG_CSharpExceptionCallback_t invalidCastCallback, SWIG_CSharpExceptionCallback_t invalidOperationCallback,
        SWIG_CSharpExceptionCallback_t ioCallback, SWIG_CSharpExceptionCallback_t nullReferenceCallback,
        SWIG_CSharpExceptionCallback_t outOfMemoryCallback, SWIG_CSharpExceptionCallback_t overflowCallback,
        SWIG_CSharpExceptionCallback_t systemCallback) {
    SWIG_csharp_exceptions[SWIG_CSharpApplicationException].callback = applicationCallback;
    SWIG_csharp_exceptions[SWIG_CSharpArithmeticException].callback = arithmeticCallback;
    SWIG_csharp_exceptions[SWIG_CSharpDivideByZeroException].callback = divideByZeroCallback;
    SWIG_csharp_exceptions[SWIG_CSharpIndexOutOfRangeException].callback = indexOutOfRangeCallback;
    SWIG_csharp_exceptions[SWIG_CSharpInvalidCastException].callback = invalidCastCallback;
    SWIG_csharp_exceptions[SWIG_CSharpInvalidOperationException].callback = invalidOperationCallback;
    SWIG_csharp_exceptions[SWIG_CSharpIOException].callback = ioCallback;
    SWIG_csharp_exceptions[SWIG_CSharpNullReferenceException].callback = nullReferenceCallback;
    SWIG_csharp_exceptions[SWIG_CSharpOutOfMemoryException].callback = outOfMemoryCallback;
    SWIG_csharp_exceptions[SWIG_CSharpOverflowException].callback = overflowCallback;
    SWIG_csharp_exceptions[SWIG_CSharpSystemException].callback = systemCallback;
}

#ifdef __cplusplus
extern "C"
#endif
    SWIGEXPORT void SWIGSTDCALL
    SWIGRegisterExceptionArgumentCallbacks_opEx(SWIG_CSharpExceptionArgumentCallback_t argumentCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentNullCallback,
                                                SWIG_CSharpExceptionArgumentCallback_t argumentOutOfRangeCallback) {
    SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentException].callback = argumentCallback;
    SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentNullException].callback = argumentNullCallback;
    SWIG_csharp_exceptions_argument[SWIG_CSharpArgumentOutOfRangeException].callback = argumentOutOfRangeCallback;
}

/* Callback for returning strings to C# without leaking memory */
typedef char *(SWIGSTDCALL *SWIG_CSharpStringHelperCallback)(const char *);
static SWIG_CSharpStringHelperCallback SWIG_csharp_string_callback = NULL;

#ifdef __cplusplus
extern "C"
#endif
    SWIGEXPORT void SWIGSTDCALL
    SWIGRegisterStringCallback_opEx(SWIG_CSharpStringHelperCallback callback) {
    SWIG_csharp_string_callback = callback;
}

/* Contract support */

#define SWIG_contract_assert(nullreturn, expr, msg)                                                                    \
    do {                                                                                                               \
        if (!(expr)) {                                                                                                 \
            SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentOutOfRangeException, msg, "");                   \
            return nullreturn;                                                                                         \
        }                                                                                                              \
    } while (0)

/* Callback for returning strings to C# without leaking memory */
typedef void *(SWIGSTDCALL *SWIG_CSharpWStringHelperCallback)(const wchar_t *, int length);
static SWIG_CSharpWStringHelperCallback SWIG_csharp_wstring_with_length_callback = NULL;

#ifdef __cplusplus
extern "C"
#endif
    SWIGEXPORT void SWIGSTDCALL
    SWIGRegisterWStringCallback_opEx(SWIG_CSharpWStringHelperCallback callback_utf16,
                                     SWIG_CSharpWStringHelperCallback callback_utf32) {
    SWIG_csharp_wstring_with_length_callback = sizeof(wchar_t) == 2 ? callback_utf16 : callback_utf32;
}

/* Callback for returning strings to C# without leaking memory */
typedef void(SWIGSTDCALL *SWIG_CSharpWStringExceptionHelperCallback)(const wchar_t *, int length);
static SWIG_CSharpWStringExceptionHelperCallback SWIG_csharp_ApplicationException_callback = NULL;

#ifdef __cplusplus
extern "C"
#endif
    SWIGEXPORT void SWIGSTDCALL
    SWIGRegisterWStringExceptionCallback_opEx(SWIG_CSharpWStringExceptionHelperCallback callback_utf16,
                                              SWIG_CSharpWStringExceptionHelperCallback callback_utf32) {
    SWIG_csharp_ApplicationException_callback = sizeof(wchar_t) == 2 ? callback_utf16 : callback_utf32;
}

#define OP_API
#include "../libop/libop.h"

#include <string>

#include <limits.h>
#include <wchar.h>
#ifndef WCHAR_MIN
#define WCHAR_MIN 0
#endif
#ifndef WCHAR_MAX
#define WCHAR_MAX 65535
#endif

static void *SWIG_csharp_wstring_callback(const wchar_t *s) {
    return SWIG_csharp_wstring_with_length_callback(s, (int)wcslen(s));
}

#include <string>

#ifdef __cplusplus
extern "C"
{
#endif

    SWIGEXPORT void SWIGSTDCALL CSharp_std_set(void *jarg1) {
        namespace arg1;
        namespace *argp1;

        argp1 = (namespace *)jarg1;
        if (!argp1) {
            SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException,
                                                   "Attempt to dereference null namespace", 0);
            return;
        }
        arg1 = *argp1;
        std = arg1;
    }

    SWIGEXPORT void *SWIGSTDCALL CSharp_std_get() {
        void *jresult;
        namespace result;

        result = std;
        {
            namespace *resultptr = (namespace *)malloc(sizeof(namespace));
            memmove(resultptr, &result, sizeof(namespace));
            jresult = resultptr;
        }
        return jresult;
    }

    SWIGEXPORT void SWIGSTDCALL CSharp_WinApi_set(void *jarg1) {
        class arg1;
        class *argp1;

        argp1 = (class *)jarg1;
        if (!argp1) {
            SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException,
                                                   "Attempt to dereference null class", 0);
            return;
        }
        arg1 = *argp1;
        WinApi = arg1;
    }

    SWIGEXPORT void *SWIGSTDCALL CSharp_WinApi_get() {
        void *jresult;
        class result;

        result = WinApi;
        {
            class *resultptr = (class *)malloc(sizeof(class));
            memmove(resultptr, &result, sizeof(class));
            jresult = resultptr;
        }
        return jresult;
    }

    SWIGEXPORT void SWIGSTDCALL CSharp_opBackground_set(void *jarg1) {
        class arg1;
        class *argp1;

        argp1 = (class *)jarg1;
        if (!argp1) {
            SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException,
                                                   "Attempt to dereference null class", 0);
            return;
        }
        arg1 = *argp1;
        opBackground = arg1;
    }

    SWIGEXPORT void *SWIGSTDCALL CSharp_opBackground_get() {
        void *jresult;
        class result;

        result = opBackground;
        {
            class *resultptr = (class *)malloc(sizeof(class));
            memmove(resultptr, &result, sizeof(class));
            jresult = resultptr;
        }
        return jresult;
    }

    SWIGEXPORT void SWIGSTDCALL CSharp_ImageProc_set(void *jarg1) {
        class arg1;
        class *argp1;

        argp1 = (class *)jarg1;
        if (!argp1) {
            SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException,
                                                   "Attempt to dereference null class", 0);
            return;
        }
        arg1 = *argp1;
        ImageProc = arg1;
    }

    SWIGEXPORT void *SWIGSTDCALL CSharp_ImageProc_get() {
        void *jresult;
        class result;

        result = ImageProc;
        {
            class *resultptr = (class *)malloc(sizeof(class));
            memmove(resultptr, &result, sizeof(class));
            jresult = resultptr;
        }
        return jresult;
    }

    SWIGEXPORT void SWIGSTDCALL CSharp_bytearray_set(void *jarg1) {
        using arg1;
        using *argp1;

        argp1 = (using *)jarg1;
        if (!argp1) {
            SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException,
                                                   "Attempt to dereference null using", 0);
            return;
        }
        arg1 = *argp1;
        bytearray = arg1;
    }

    SWIGEXPORT void *SWIGSTDCALL CSharp_bytearray_get() {
        void *jresult;
        using result;

        result = bytearray;
        {
            using *resultptr = (using *)malloc(sizeof(using));
            memmove(resultptr, &result, sizeof(using));
            jresult = resultptr;
        }
        return jresult;
    }

    SWIGEXPORT void SWIGSTDCALL CSharp_libop_set(void *jarg1) {
        class arg1;
        class *argp1;

        argp1 = (class *)jarg1;
        if (!argp1) {
            SWIG_CSharpSetPendingExceptionArgument(SWIG_CSharpArgumentNullException,
                                                   "Attempt to dereference null class", 0);
            return;
        }
        arg1 = *argp1;
        libop = arg1;
    }

    SWIGEXPORT void *SWIGSTDCALL CSharp_libop_get() {
        void *jresult;
        class result;

        result = libop;
        {
            class *resultptr = (class *)malloc(sizeof(class));
            memmove(resultptr, &result, sizeof(class));
            jresult = resultptr;
        }
        return jresult;
    }

#ifdef __cplusplus
}
#endif
