# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _opEx
else:
    import _opEx

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class libop(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, hinst=None):
        _opEx.libop_swiginit(self, _opEx.new_libop(hinst))
    __swig_destroy__ = _opEx.delete_libop

    def Ver(self):
        return _opEx.libop_Ver(self)

    def SetPath(self, path, ret):
        return _opEx.libop_SetPath(self, path, ret)

    def GetPath(self, path):
        return _opEx.libop_GetPath(self, path)

    def GetBasePath(self, path):
        return _opEx.libop_GetBasePath(self, path)

    def GetID(self, ret):
        return _opEx.libop_GetID(self, ret)

    def GetLastError(self, ret):
        return _opEx.libop_GetLastError(self, ret)

    def SetShowErrorMsg(self, show_type, ret):
        return _opEx.libop_SetShowErrorMsg(self, show_type, ret)

    def Sleep(self, millseconds, ret):
        return _opEx.libop_Sleep(self, millseconds, ret)

    def InjectDll(self, process_name, dll_name, ret):
        return _opEx.libop_InjectDll(self, process_name, dll_name, ret)

    def EnablePicCache(self, enable, ret):
        return _opEx.libop_EnablePicCache(self, enable, ret)

    def CapturePre(self, file_name, ret):
        return _opEx.libop_CapturePre(self, file_name, ret)

    def AStarFindPath(self, mapWidth, mapHeight, disable_points, beginX, beginY, endX, endY, path):
        return _opEx.libop_AStarFindPath(self, mapWidth, mapHeight, disable_points, beginX, beginY, endX, endY, path)

    def FindNearestPos(self, all_pos, type, x, y, retstr):
        return _opEx.libop_FindNearestPos(self, all_pos, type, x, y, retstr)

    def EnumWindow(self, parent, title, class_name, filter, retstr):
        return _opEx.libop_EnumWindow(self, parent, title, class_name, filter, retstr)

    def EnumWindowByProcess(self, process_name, title, class_name, filter, retstring):
        return _opEx.libop_EnumWindowByProcess(self, process_name, title, class_name, filter, retstring)

    def EnumProcess(self, name, retstring):
        return _opEx.libop_EnumProcess(self, name, retstring)

    def ClientToScreen(self, ClientToScreen, x, y, bret):
        return _opEx.libop_ClientToScreen(self, ClientToScreen, x, y, bret)

    def FindWindow(self, class_name, title, rethwnd):
        return _opEx.libop_FindWindow(self, class_name, title, rethwnd)

    def FindWindowByProcess(self, process_name, class_name, title, rethwnd):
        return _opEx.libop_FindWindowByProcess(self, process_name, class_name, title, rethwnd)

    def FindWindowByProcessId(self, process_id, class_name, title, rethwnd):
        return _opEx.libop_FindWindowByProcessId(self, process_id, class_name, title, rethwnd)

    def FindWindowEx(self, parent, class_name, title, rethwnd):
        return _opEx.libop_FindWindowEx(self, parent, class_name, title, rethwnd)

    def GetClientRect(self, hwnd, x1, y1, x2, y2, nret):
        return _opEx.libop_GetClientRect(self, hwnd, x1, y1, x2, y2, nret)

    def GetClientSize(self, hwnd, width, height, nret):
        return _opEx.libop_GetClientSize(self, hwnd, width, height, nret)

    def GetForegroundFocus(self, rethwnd):
        return _opEx.libop_GetForegroundFocus(self, rethwnd)

    def GetForegroundWindow(self, rethwnd):
        return _opEx.libop_GetForegroundWindow(self, rethwnd)

    def GetMousePointWindow(self, rethwnd):
        return _opEx.libop_GetMousePointWindow(self, rethwnd)

    def GetPointWindow(self, x, y, rethwnd):
        return _opEx.libop_GetPointWindow(self, x, y, rethwnd)

    def GetProcessInfo(self, pid, retstring):
        return _opEx.libop_GetProcessInfo(self, pid, retstring)

    def GetSpecialWindow(self, flag, rethwnd):
        return _opEx.libop_GetSpecialWindow(self, flag, rethwnd)

    def GetWindow(self, hwnd, flag, nret):
        return _opEx.libop_GetWindow(self, hwnd, flag, nret)

    def GetWindowClass(self, hwnd, retstring):
        return _opEx.libop_GetWindowClass(self, hwnd, retstring)

    def GetWindowProcessId(self, hwnd, nretpid):
        return _opEx.libop_GetWindowProcessId(self, hwnd, nretpid)

    def GetWindowProcessPath(self, hwnd, retstring):
        return _opEx.libop_GetWindowProcessPath(self, hwnd, retstring)

    def GetWindowRect(self, hwnd, x1, y1, x2, y2, nret):
        return _opEx.libop_GetWindowRect(self, hwnd, x1, y1, x2, y2, nret)

    def GetWindowState(self, hwnd, flag, rethwnd):
        return _opEx.libop_GetWindowState(self, hwnd, flag, rethwnd)

    def GetWindowTitle(self, hwnd, rettitle):
        return _opEx.libop_GetWindowTitle(self, hwnd, rettitle)

    def MoveWindow(self, hwnd, x, y, nret):
        return _opEx.libop_MoveWindow(self, hwnd, x, y, nret)

    def ScreenToClient(self, hwnd, x, y, nret):
        return _opEx.libop_ScreenToClient(self, hwnd, x, y, nret)

    def SendPaste(self, hwnd, nret):
        return _opEx.libop_SendPaste(self, hwnd, nret)

    def SetClientSize(self, hwnd, width, hight, nret):
        return _opEx.libop_SetClientSize(self, hwnd, width, hight, nret)

    def SetWindowState(self, hwnd, flag, nret):
        return _opEx.libop_SetWindowState(self, hwnd, flag, nret)

    def SetWindowSize(self, hwnd, width, height, nret):
        return _opEx.libop_SetWindowSize(self, hwnd, width, height, nret)

    def SetWindowText(self, hwnd, title, nret):
        return _opEx.libop_SetWindowText(self, hwnd, title, nret)

    def SetWindowTransparent(self, hwnd, trans, nret):
        return _opEx.libop_SetWindowTransparent(self, hwnd, trans, nret)

    def SendString(self, hwnd, str, ret):
        return _opEx.libop_SendString(self, hwnd, str, ret)

    def SendStringIme(self, hwnd, str, ret):
        return _opEx.libop_SendStringIme(self, hwnd, str, ret)

    def RunApp(self, cmdline, mode, ret):
        return _opEx.libop_RunApp(self, cmdline, mode, ret)

    def WinExec(self, cmdline, cmdshow, ret):
        return _opEx.libop_WinExec(self, cmdline, cmdshow, ret)

    def GetCmdStr(self, cmd, millseconds, retstr):
        return _opEx.libop_GetCmdStr(self, cmd, millseconds, retstr)

    def BindWindow(self, hwnd, display, mouse, keypad, mode, ret):
        return _opEx.libop_BindWindow(self, hwnd, display, mouse, keypad, mode, ret)

    def UnBindWindow(self, ret):
        return _opEx.libop_UnBindWindow(self, ret)

    def GetCursorPos(self, x, y, ret):
        return _opEx.libop_GetCursorPos(self, x, y, ret)

    def MoveR(self, x, y, ret):
        return _opEx.libop_MoveR(self, x, y, ret)

    def MoveTo(self, x, y, ret):
        return _opEx.libop_MoveTo(self, x, y, ret)

    def MoveToEx(self, x, y, w, h, ret):
        return _opEx.libop_MoveToEx(self, x, y, w, h, ret)

    def LeftClick(self, ret):
        return _opEx.libop_LeftClick(self, ret)

    def LeftDoubleClick(self, ret):
        return _opEx.libop_LeftDoubleClick(self, ret)

    def LeftDown(self, ret):
        return _opEx.libop_LeftDown(self, ret)

    def LeftUp(self, ret):
        return _opEx.libop_LeftUp(self, ret)

    def MiddleClick(self, ret):
        return _opEx.libop_MiddleClick(self, ret)

    def MiddleDown(self, ret):
        return _opEx.libop_MiddleDown(self, ret)

    def MiddleUp(self, ret):
        return _opEx.libop_MiddleUp(self, ret)

    def RightClick(self, ret):
        return _opEx.libop_RightClick(self, ret)

    def RightDown(self, ret):
        return _opEx.libop_RightDown(self, ret)

    def RightUp(self, ret):
        return _opEx.libop_RightUp(self, ret)

    def WheelDown(self, ret):
        return _opEx.libop_WheelDown(self, ret)

    def WheelUp(self, ret):
        return _opEx.libop_WheelUp(self, ret)

    def GetKeyState(self, vk_code, ret):
        return _opEx.libop_GetKeyState(self, vk_code, ret)

    def KeyDown(self, vk_code, ret):
        return _opEx.libop_KeyDown(self, vk_code, ret)

    def KeyDownChar(self, vk_code, ret):
        return _opEx.libop_KeyDownChar(self, vk_code, ret)

    def KeyUp(self, vk_code, ret):
        return _opEx.libop_KeyUp(self, vk_code, ret)

    def KeyUpChar(self, vk_code, ret):
        return _opEx.libop_KeyUpChar(self, vk_code, ret)

    def WaitKey(self, vk_code, time_out, ret):
        return _opEx.libop_WaitKey(self, vk_code, time_out, ret)

    def KeyPress(self, vk_code, ret):
        return _opEx.libop_KeyPress(self, vk_code, ret)

    def KeyPressChar(self, vk_code, ret):
        return _opEx.libop_KeyPressChar(self, vk_code, ret)

    def Capture(self, x1, y1, x2, y2, file_name, ret):
        return _opEx.libop_Capture(self, x1, y1, x2, y2, file_name, ret)

    def CmpColor(self, x, y, color, sim, ret):
        return _opEx.libop_CmpColor(self, x, y, color, sim, ret)

    def FindColor(self, x1, y1, x2, y2, color, sim, dir, x, y, ret):
        return _opEx.libop_FindColor(self, x1, y1, x2, y2, color, sim, dir, x, y, ret)

    def FindColorEx(self, x1, y1, x2, y2, color, sim, dir, retstr):
        return _opEx.libop_FindColorEx(self, x1, y1, x2, y2, color, sim, dir, retstr)

    def FindMultiColor(self, x1, y1, x2, y2, first_color, offset_color, sim, dir, x, y, ret):
        return _opEx.libop_FindMultiColor(self, x1, y1, x2, y2, first_color, offset_color, sim, dir, x, y, ret)

    def FindMultiColorEx(self, x1, y1, x2, y2, first_color, offset_color, sim, dir, retstr):
        return _opEx.libop_FindMultiColorEx(self, x1, y1, x2, y2, first_color, offset_color, sim, dir, retstr)

    def FindPic(self, x1, y1, x2, y2, files, delta_color, sim, dir, x, y, ret):
        return _opEx.libop_FindPic(self, x1, y1, x2, y2, files, delta_color, sim, dir, x, y, ret)

    def FindPicEx(self, x1, y1, x2, y2, files, delta_color, sim, dir, retstr):
        return _opEx.libop_FindPicEx(self, x1, y1, x2, y2, files, delta_color, sim, dir, retstr)

    def FindPicExS(self, x1, y1, x2, y2, files, delta_color, sim, dir, retstr):
        return _opEx.libop_FindPicExS(self, x1, y1, x2, y2, files, delta_color, sim, dir, retstr)

    def GetColor(self, x, y, ret):
        return _opEx.libop_GetColor(self, x, y, ret)

    def SetDisplayInput(self, mode, ret):
        return _opEx.libop_SetDisplayInput(self, mode, ret)

    def LoadPic(self, file_name, ret):
        return _opEx.libop_LoadPic(self, file_name, ret)

    def FreePic(self, file_name, ret):
        return _opEx.libop_FreePic(self, file_name, ret)

    def LoadMemPic(self, file_name, data, size, ret):
        return _opEx.libop_LoadMemPic(self, file_name, data, size, ret)

    def GetScreenData(self, x1, y1, x2, y2, data, ret):
        return _opEx.libop_GetScreenData(self, x1, y1, x2, y2, data, ret)

    def GetScreenDataBmp(self, x1, y1, x2, y2, data, size, ret):
        return _opEx.libop_GetScreenDataBmp(self, x1, y1, x2, y2, data, size, ret)

    def GetScreenFrameInfo(self, frame_id, time):
        return _opEx.libop_GetScreenFrameInfo(self, frame_id, time)

    def MatchPicName(self, pic_name, retstr):
        return _opEx.libop_MatchPicName(self, pic_name, retstr)

    def SetDict(self, idx, file_name, ret):
        return _opEx.libop_SetDict(self, idx, file_name, ret)

    def SetMemDict(self, idx, data, size, ret):
        return _opEx.libop_SetMemDict(self, idx, data, size, ret)

    def UseDict(self, idx, ret):
        return _opEx.libop_UseDict(self, idx, ret)

    def Ocr(self, x1, y1, x2, y2, color, sim, ret_str):
        return _opEx.libop_Ocr(self, x1, y1, x2, y2, color, sim, ret_str)

    def OcrEx(self, x1, y1, x2, y2, color, sim, ret_str):
        return _opEx.libop_OcrEx(self, x1, y1, x2, y2, color, sim, ret_str)

    def FindStr(self, x1, y1, x2, y2, strs, color, sim, retx, rety, ret):
        return _opEx.libop_FindStr(self, x1, y1, x2, y2, strs, color, sim, retx, rety, ret)

    def FindStrEx(self, x1, y1, x2, y2, strs, color, sim, retstr):
        return _opEx.libop_FindStrEx(self, x1, y1, x2, y2, strs, color, sim, retstr)

    def OcrAuto(self, x1, y1, x2, y2, sim, ret_str):
        return _opEx.libop_OcrAuto(self, x1, y1, x2, y2, sim, ret_str)

    def OcrFromFile(self, file_name, color_format, sim, retstr):
        return _opEx.libop_OcrFromFile(self, file_name, color_format, sim, retstr)

    def OcrAutoFromFile(self, file_name, sim, retstr):
        return _opEx.libop_OcrAutoFromFile(self, file_name, sim, retstr)

    def FindLine(self, x1, y1, x2, y2, color, sim, retstr):
        return _opEx.libop_FindLine(self, x1, y1, x2, y2, color, sim, retstr)

    def WriteData(self, hwnd, address, data, size, ret):
        return _opEx.libop_WriteData(self, hwnd, address, data, size, ret)

    def ReadData(self, hwnd, address, size, retstr):
        return _opEx.libop_ReadData(self, hwnd, address, size, retstr)

# Register libop in _opEx:
_opEx.libop_swigregister(libop)



